<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice</title>
    <!-- Add any CSS styles specific to your PDF here -->
    <style>
        /* Example styles for the PDF content */
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        h1 {
            font-size: 24px;
            text-align: center;
        }

        p {
            font-size: 14px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        /* Style for the image */
        .invoice-image {
            max-width: 100%;
            height: auto;
        }
    </style>
</head>
<body>
    <h1>Invoice</h1>
    <!-- Include the image using an <img> tag -->
    {{-- <img class="invoice-image" src="{{ $invoiceData['image'] }}" alt="Invoice Image"> --}}
    <img class="invoice-image" src="{{ $invoiceData['image'] }}" width="200" alt="Invoice Image">
    <p>Date: {{ $invoiceData['date'] }}</p>
    <p>Generated By: {{ $invoiceData['generatedBy'] }}</p>
    <p>Invoice Sent To: {{ $invoiceData['sentTo'] }}</p>
    <table>
        <thead>
            <tr>
                <th>Description</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($invoiceData['lineItems'] as $item)
                <tr>
                    <td>{{ $item['description'] }}</td>
                    <td>${{ number_format($item['amount'], 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>
